// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FBXModel.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class FBXModel_node;
@class FBXModel_node_animationMatrix;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - FbxmodelRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface FbxmodelRoot : GPBRootObject
@end

#pragma mark - FBXModel

typedef GPB_ENUM(FBXModel_FieldNumber) {
  FBXModel_FieldNumber_NodesArray = 1,
};

/**
 *
 * FBXModel.proto.strings
 * FBX Integration
 *
 * Created by Kunal Thacker on 21/06/17.
 * Copyright © 2017 Kunal Thacker. All rights reserved.
 **/
@interface FBXModel : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FBXModel_node*> *nodesArray;
/** The number of items in @c nodesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger nodesArray_Count;

@end

#pragma mark - FBXModel_node

typedef GPB_ENUM(FBXModel_node_FieldNumber) {
  FBXModel_node_FieldNumber_VerticesArray = 1,
  FBXModel_node_FieldNumber_UvCoordsArray = 2,
  FBXModel_node_FieldNumber_IndicesArray = 3,
  FBXModel_node_FieldNumber_MatricesArray = 4,
};

@interface FBXModel_node : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *verticesArray;
/** The number of items in @c verticesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger verticesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBFloatArray *uvCoordsArray;
/** The number of items in @c uvCoordsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger uvCoordsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) GPBInt32Array *indicesArray;
/** The number of items in @c indicesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger indicesArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FBXModel_node_animationMatrix*> *matricesArray;
/** The number of items in @c matricesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger matricesArray_Count;

@end

#pragma mark - FBXModel_node_animationMatrix

typedef GPB_ENUM(FBXModel_node_animationMatrix_FieldNumber) {
  FBXModel_node_animationMatrix_FieldNumber_ValuesArray = 1,
};

@interface FBXModel_node_animationMatrix : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) GPBDoubleArray *valuesArray;
/** The number of items in @c valuesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger valuesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
